Fix typos
w3c-cg/rdfsurfaces pull request #10
Opened 2024-05-13 09:53 UTC by joachimvh

I specifically wanted to fix example 22 where it states that `∀ _:X : _:X a :Person AND _:X :knows :Alice` is equivalent to `"Every person knows Alice"`, while it should be `"Everything is a person and knows Alice"`. Besides that I also fixed some typos that I found. My IDE also wanted to remove all trailing spaces on many lines but I refrained from doing that as I didn't know what the preference would be.

2024-05-13 14:24 UTC, TallTed requested changes
Typos within typos...

2024-05-13 14:24 UTC, TallTed commented on index.html
> +or more RDF graphs written on a <em>negative</em> surface they mean the negation of those RDF graphs.</p>
```suggestion
or more RDF graphs written on a <em>negative</em> surface, they mean the negation of those RDF graphs.</p>
```

2024-05-13 14:24 UTC, TallTed commented on index.html
> +that is a <code>:City</code>, it implies that <code>_:S</code> also needs to be a <code>:HumanCommunity</code>.</p>
```suggestion
that is a <code>:City</code>, it is implied that <code>_:S</code> is also a <code>:HumanCommunity</code>.</p>
```

2024-05-13 14:24 UTC, TallTed commented on index.html
> +the kind of surface. Any kind of surface may be used but the following built-ins have
```suggestion
the kind of surface. Any kind of surface may be used, but the following built-ins have 
```

2024-05-13 14:24 UTC, TallTed commented on index.html
> +Nested surfaces can share the same <a data-link-type="biblio" href="#biblio-uri" title="Uniform Resource Identifier (URI): Generic Syntax">[URI]</a>s and literals (by copying the data),
```suggestion
Nested surfaces can share the same <a data-link-type="biblio" href="#biblio-uri" title="Uniform Resource Identifier (URI): Generic Syntax">[URI]s</a> and literals (by copying the data), 
```

2024-05-13 14:24 UTC, TallTed commented on index.html
> +   <p>In RDF Surfaces a default positive surface is implicitly assumed for each RDF document. On this default positive surface all existential variables are implicitly quantified. Example 20 can be r
```suggestion
   <p>In RDF Surfaces, a default positive surface is implicitly assumed for each RDF document. On this default positive surface, all existential variables are implicitly quantified. Example 20 can be rewritten as:</p>
```

2024-05-13 14:24 UTC, TallTed commented on index.html
> +   <p>When a blank node is marked on an odd nested negative surface, then it is interpreted as a universal quantified variable in the scope of the nested surface.</p>
```suggestion
   <p>When a blank node is marked on an odd nested negative surface, it is interpreted as a universal quantified variable in the scope of the nested surface.</p>
```

2024-05-13 14:24 UTC, TallTed commented on index.html
> +interpretation of the negative surface is the negation of RDF Graph on it.</p>
```suggestion
interpretation of the negative surface is the negation of the RDF Graph on it.</p>
```

2024-05-13 14:24 UTC, TallTed commented on index.html
> +   <p>With combinations of AND and NOT other logical truth function can be built. E.g.</p>
```suggestion
   <p>With combinations of AND and NOT, other logical truth functions can be built, such as the following:</p>
```

2024-05-13 16:41 UTC, merged

2024-05-13 16:42 UTC, phochste commented
Thanks @joachimvh  and @TallTed  for the fixes & fixes of fixes.

2024-05-13 16:59 UTC, TallTed commented
What is the actual "source" file here, the `.html` or the `.bs`? I want to fix the one that is meant to be human-edited, such that those fixes get carried into the machine-generated.

2024-05-13 17:29 UTC, phochste commented
@TallTed The source file is `index.bs`. We don't have automatic builds yet. A `make web` generates the `index.html` from the `index.bs`. If you have any other additions you can create a pull request for the `index.bs`.

2024-05-14 07:04 UTC, joachimvh commented
> @TallTed The source file is `index.bs`. We don't have automatic builds yet. A `make web` generates the `index.html` from the `index.bs`. If you have any other additions you can create a pull request for the `index.bs`.

Doesn't that mean that my PR here is wrong and the `index.bs` file should have been edited instead? I missed that there was one.

2024-05-14 07:46 UTC, phochste commented
@joachimvh yes, I think you need to add a new pull request.